# Generated by Django 4.1.5 on 2024-02-09 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='infoBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=150)),
                ('lot', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('codepostal', models.CharField(max_length=150)),
                ('fax', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='produitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='produitRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, null=True)),
                ('produitcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.produitcategory')),
            ],
        ),
        migrations.CreateModel(
            name='produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('prix', models.CharField(max_length=150, null=True)),
                ('devise', models.CharField(max_length=150, null=True)),
                ('photo_p', models.FileField(max_length=200, upload_to='')),
                ('photo_s', models.FileField(max_length=200, upload_to='')),
                ('photo_tr', models.FileField(max_length=200, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.DateTimeField(auto_now=True)),
                ('produit_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.produitcategory')),
                ('produit_race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.produitrace')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('iso', models.CharField(max_length=150)),
                ('liens', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subscribModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('pack', models.CharField(default='null', max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('commentaire', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='produitStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_debut', models.CharField(max_length=150, null=True)),
                ('nbr_consomme', models.CharField(max_length=150, null=True)),
                ('nbr_reste', models.CharField(max_length=150, null=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.produits')),
            ],
        ),
    ]
