# Generated by Django 4.1.5 on 2024-02-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='packtandegna',
        ),
    ]
