# Generated by Django 4.1.5 on 2023-03-28 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=15)),
                ('ages', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('poids', models.CharField(max_length=10)),
                ('options', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('regions', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('communes', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=10)),
                ('puce', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='')),
                ('image2', models.FileField(upload_to='')),
                ('image3', models.FileField(upload_to='')),
                ('image4', models.FileField(upload_to='')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tandegna.article')),
            ],
        ),
    ]
