# Generated by Django 4.1.5 on 2023-04-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tandegna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.DateTimeField(auto_created=True)),
                ('nombre', models.CharField(max_length=100)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tandegna.article')),
            ],
        ),
    ]
