# Generated by Django 4.1.5 on 2023-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tandegna', '0002_alter_stock_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='TandegnaArticle_slugSpecialeVraiment+match=idpv_', max_length=250),
        ),
    ]
