# Generated by Django 4.1.5 on 2023-04-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tandegna', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_by',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
