# Generated by Django 4.1.5 on 2023-04-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tandegna', '0003_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='devise',
            field=models.CharField(default='Ar', max_length=20),
        ),
    ]
