# Generated by Django 4.1.5 on 2023-05-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tandegna', '0004_article_devise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
