# Generated by Django 4.1.5 on 2023-05-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tandegna', '0005_delete_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type',
            new_name='categories',
        ),
    ]
